
package com.atos.wsdl.pmisdwh.meteringQuery;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MeteringQueryWsImplService", targetNamespace = "http://message.ws.atos.com/", wsdlLocation = "http://10.104.239.127/TPAWS/MeteringQueryWs.svc?wsdl")
public class MeteringQueryWsImplService_Service
    extends Service
{

    private final static URL METERINGQUERYWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException METERINGQUERYWSIMPLSERVICE_EXCEPTION;
    private final static QName METERINGQUERYWSIMPLSERVICE_QNAME = new QName("http://message.ws.atos.com/", "MeteringQueryWsImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.104.239.127/TPAWS/MeteringQueryWs.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        METERINGQUERYWSIMPLSERVICE_WSDL_LOCATION = url;
        METERINGQUERYWSIMPLSERVICE_EXCEPTION = e;
    }

    public MeteringQueryWsImplService_Service() {
        super(__getWsdlLocation(), METERINGQUERYWSIMPLSERVICE_QNAME);
    }

    public MeteringQueryWsImplService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), METERINGQUERYWSIMPLSERVICE_QNAME, features);
    }

    public MeteringQueryWsImplService_Service(URL wsdlLocation) {
        super(wsdlLocation, METERINGQUERYWSIMPLSERVICE_QNAME);
    }

    public MeteringQueryWsImplService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, METERINGQUERYWSIMPLSERVICE_QNAME, features);
    }

    public MeteringQueryWsImplService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MeteringQueryWsImplService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MeteringQueryWsImplService
     */
    @WebEndpoint(name = "BasicHttpBinding_MeteringQueryWsImplService")
    public MeteringQueryWsImplService getBasicHttpBindingMeteringQueryWsImplService() {
        return super.getPort(new QName("http://message.ws.atos.com/", "BasicHttpBinding_MeteringQueryWsImplService"), MeteringQueryWsImplService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MeteringQueryWsImplService
     */
    @WebEndpoint(name = "BasicHttpBinding_MeteringQueryWsImplService")
    public MeteringQueryWsImplService getBasicHttpBindingMeteringQueryWsImplService(WebServiceFeature... features) {
        return super.getPort(new QName("http://message.ws.atos.com/", "BasicHttpBinding_MeteringQueryWsImplService"), MeteringQueryWsImplService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (METERINGQUERYWSIMPLSERVICE_EXCEPTION!= null) {
            throw METERINGQUERYWSIMPLSERVICE_EXCEPTION;
        }
        return METERINGQUERYWSIMPLSERVICE_WSDL_LOCATION;
    }

}
