
package com.atos.wsdl.pmisdwh.meteringQuery;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MeteringQueryWsImplService", targetNamespace = "http://message.ws.atos.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MeteringQueryWsImplService {


    /**
     * 
     * @param request
     * @return
     *     returns com.atos.wsdl.pmisdwh.meteringQuery.MeteringQueryResponse
     */
    @WebMethod(action = "http://message.ws.atos.com/MeteringQueryWsImplService/processMessage")
    @WebResult(name = "processMessageResult", targetNamespace = "http://message.ws.atos.com/")
    @RequestWrapper(localName = "processMessage", targetNamespace = "http://message.ws.atos.com/", className = "com.atos.wsdl.pmisdwh.meteringQuery.ProcessMessage")
    @ResponseWrapper(localName = "processMessageResponse", targetNamespace = "http://message.ws.atos.com/", className = "com.atos.wsdl.pmisdwh.meteringQuery.ProcessMessageResponse")
    public MeteringQueryResponse processMessage(
        @WebParam(name = "request", targetNamespace = "http://message.ws.atos.com/")
        ProcessMessageCls request);

}
