
package com.atos.wsdl.pmisdwh.baseinventory;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BaseInventory", targetNamespace = "http://message.ws.atos.com/", wsdlLocation = "file:/C:/eclipses/eclipse-jee-2019/workspace/gs-consuming-web-service-main/initial/src/main/resources/wsdl/BaseInventory.wsdl")
public class BaseInventory
    extends Service
{

    private final static URL BASEINVENTORY_WSDL_LOCATION;
    private final static WebServiceException BASEINVENTORY_EXCEPTION;
    private final static QName BASEINVENTORY_QNAME = new QName("http://message.ws.atos.com/", "BaseInventory");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/eclipses/eclipse-jee-2019/workspace/gs-consuming-web-service-main/initial/src/main/resources/wsdl/BaseInventory.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BASEINVENTORY_WSDL_LOCATION = url;
        BASEINVENTORY_EXCEPTION = e;
    }

    public BaseInventory() {
        super(__getWsdlLocation(), BASEINVENTORY_QNAME);
    }

    public BaseInventory(WebServiceFeature... features) {
        super(__getWsdlLocation(), BASEINVENTORY_QNAME, features);
    }

    public BaseInventory(URL wsdlLocation) {
        super(wsdlLocation, BASEINVENTORY_QNAME);
    }

    public BaseInventory(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BASEINVENTORY_QNAME, features);
    }

    public BaseInventory(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BaseInventory(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BaseInventoryImplService
     */
    @WebEndpoint(name = "BasicHttpBinding_BaseInventoryImplService")
    public BaseInventoryImplService getBasicHttpBindingBaseInventoryImplService() {
        return super.getPort(new QName("http://message.ws.atos.com/", "BasicHttpBinding_BaseInventoryImplService"), BaseInventoryImplService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BaseInventoryImplService
     */
    @WebEndpoint(name = "BasicHttpBinding_BaseInventoryImplService")
    public BaseInventoryImplService getBasicHttpBindingBaseInventoryImplService(WebServiceFeature... features) {
        return super.getPort(new QName("http://message.ws.atos.com/", "BasicHttpBinding_BaseInventoryImplService"), BaseInventoryImplService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BASEINVENTORY_EXCEPTION!= null) {
            throw BASEINVENTORY_EXCEPTION;
        }
        return BASEINVENTORY_WSDL_LOCATION;
    }

}
