
package com.atos.wsdl.pmisdwh.acuminventory;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AccumInventoryImplService", targetNamespace = "http://message.ws.atos.com/", wsdlLocation = "file:/C:/eclipses/eclipse-jee-2019/workspace/gs-consuming-web-service-main/initial/src/main/resources/wsdl/AccumInventory.wsdl")
public class AccumInventoryImplService_Service
    extends Service
{

    private final static URL ACCUMINVENTORYIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ACCUMINVENTORYIMPLSERVICE_EXCEPTION;
    private final static QName ACCUMINVENTORYIMPLSERVICE_QNAME = new QName("http://message.ws.atos.com/", "AccumInventoryImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/eclipses/eclipse-jee-2019/workspace/gs-consuming-web-service-main/initial/src/main/resources/wsdl/AccumInventory.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACCUMINVENTORYIMPLSERVICE_WSDL_LOCATION = url;
        ACCUMINVENTORYIMPLSERVICE_EXCEPTION = e;
    }

    public AccumInventoryImplService_Service() {
        super(__getWsdlLocation(), ACCUMINVENTORYIMPLSERVICE_QNAME);
    }

    public AccumInventoryImplService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACCUMINVENTORYIMPLSERVICE_QNAME, features);
    }

    public AccumInventoryImplService_Service(URL wsdlLocation) {
        super(wsdlLocation, ACCUMINVENTORYIMPLSERVICE_QNAME);
    }

    public AccumInventoryImplService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACCUMINVENTORYIMPLSERVICE_QNAME, features);
    }

    public AccumInventoryImplService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccumInventoryImplService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AccumInventoryImplService
     */
    @WebEndpoint(name = "BasicHttpBinding_AccumInventoryImplService")
    public AccumInventoryImplService getBasicHttpBindingAccumInventoryImplService() {
        return super.getPort(new QName("http://message.ws.atos.com/", "BasicHttpBinding_AccumInventoryImplService"), AccumInventoryImplService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccumInventoryImplService
     */
    @WebEndpoint(name = "BasicHttpBinding_AccumInventoryImplService")
    public AccumInventoryImplService getBasicHttpBindingAccumInventoryImplService(WebServiceFeature... features) {
        return super.getPort(new QName("http://message.ws.atos.com/", "BasicHttpBinding_AccumInventoryImplService"), AccumInventoryImplService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACCUMINVENTORYIMPLSERVICE_EXCEPTION!= null) {
            throw ACCUMINVENTORYIMPLSERVICE_EXCEPTION;
        }
        return ACCUMINVENTORYIMPLSERVICE_WSDL_LOCATION;
    }

}
